# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

stages:
  # - stylecheck
  # - build with gcc
  - build with clang
  - test

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - build/programs
    - build/src
  policy: pull-push

style check:
  stage: stylecheck
  tags:
    - "test"
  script:
    - export cur_dir=`pwd`
    - echo "current dir is $cur_dir"
    - cd tests/ci
    - python3 code_style_check.py
    - echo "code style check success!"
  allow_failure: true

build with gcc:
  stage: build with gcc
  tags:
    - "test"
  script:
    - git submodule sync
    - git submodule update --init --recursive

    - export CC=gcc-10
    - export CXX=g++-10

    - mkdir build_gcc
    - cd build_gcc
    - export build_dir=`pwd`
    - echo "build dir is $build_dir"
    - cmake ..
    - ninja
    - echo "Build with gcc success!"

build with clang:
  stage: build with clang
  cache:
    <<: *global_cache
    policy: push
  tags:
    - "test"
  script:
    - git submodule sync
    - git submodule update --init --recursive
    - export CC=clang-11
    - export CXX=clang++-11

    - mkdir build
    - cd build
    - export build_dir=`pwd`
    - echo "build dir is $build_dir"
    - cmake ..
    - ninja
    - echo "Build success!"

tests:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  tags:
    - "test"
  script:
    - cd build
    - export cur_dir=`pwd`
    - echo "current dir is $cur_dir"

    - ./src/unit_tests_dbms --gtest_filter="Raft*"
    - echo "Unit test finished."

    - echo "Start integration tests"
    - cd ../tests/integration
    - export integration_work_dir=`pwd`
    - export CLICKHOUSE_TESTS_ODBC_BRIDGE_BIN_PATH=$build_dir/programs/clickhouse-odbc-bridge
    - export CLICKHOUSE_TESTS_SERVER_BIN_PATH=$build_dir/programs/clickhouse
    - export CLICKHOUSE_TESTS_CLIENT_BIN_PATH=$build_dir/programs/clickhouse
    - export CLICKHOUSE_TESTS_BASE_CONFIG_DIR=$build_dir/../programs/server
    - ./runner 'test_servicekeeper_* -ss'
    - echo "Integration test finished."


    - echo "Start performance test."
    - cd ../../benchmark/raft-benchmark
    - mvn clean compile package
    - cd ../../tests/integration
    - ./runner 'test_servicekeeperperformance -ss'
